package tk.mybatis.simple.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table country
 */
public class CountryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}